spring.application.name=bank-core-api

server.port=8080

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/banco_xyz_core?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Actuator / observabilidad
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
