server.port=8080
banco.xyz.config.origen=Config Server Semana 7

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
