server.port=8080
banco.xyz.config.origen=Config Server Semana 7

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Kafka - arquitectura orientada a eventos
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all

banco.kafka.topic.movimientos=banco.movimientos
