spring.application.name=bff-web

server.port=8081

# API interna Banco XYZ
core.api.base-url=http://localhost:8080

# Observabilidad
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
# JWT Web
security.jwt.secret=${WEB_JWT_SECRET}
security.jwt.issuer=bff-web
security.jwt.expiration-minutes=30

# Credenciales Web
security.auth.username=${WEB_AUTH_USERNAME}
security.auth.password=${WEB_AUTH_PASSWORD}
# HTTPS
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz-local