spring.application.name=authorization-server
server.port=9000

spring.security.oauth2.authorizationserver.issuer=${AUTH_ISSUER:http://localhost:9000}

# Cliente Web
spring.security.oauth2.authorizationserver.client.web.registration.client-id=banco-web
spring.security.oauth2.authorizationserver.client.web.registration.client-secret={noop}${OAUTH_WEB_CLIENT_SECRET}
spring.security.oauth2.authorizationserver.client.web.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.web.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.web.registration.scopes[0]=WEB_ACCESS

# Cliente Mobile
spring.security.oauth2.authorizationserver.client.mobile.registration.client-id=banco-mobile
spring.security.oauth2.authorizationserver.client.mobile.registration.client-secret={noop}${OAUTH_MOBILE_CLIENT_SECRET}
spring.security.oauth2.authorizationserver.client.mobile.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.mobile.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.mobile.registration.scopes[0]=MOBILE_ACCESS

# Cliente ATM
spring.security.oauth2.authorizationserver.client.atm.registration.client-id=banco-atm
spring.security.oauth2.authorizationserver.client.atm.registration.client-secret={noop}${OAUTH_ATM_CLIENT_SECRET}
spring.security.oauth2.authorizationserver.client.atm.registration.client-authentication-methods[0]=client_secret_basic
spring.security.oauth2.authorizationserver.client.atm.registration.authorization-grant-types[0]=client_credentials
spring.security.oauth2.authorizationserver.client.atm.registration.scopes[0]=ATM_ACCESS

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always