spring.application.name=bff-mobile

server.port=8082

# API interna Banco XYZ
core.api.base-url=http://localhost:8080

# Observabilidad
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
# JWT Mobile
security.jwt.secret=${MOBILE_JWT_SECRET}
security.jwt.issuer=bff-mobile
security.jwt.expiration-minutes=30

# Credenciales Mobile
security.auth.username=${MOBILE_AUTH_USERNAME}
security.auth.password=${MOBILE_AUTH_PASSWORD}
# HTTPS
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz-local