spring.application.name=bff-atm

server.port=8083

# API interna Banco XYZ
core.api.base-url=http://localhost:8080

# Observabilidad
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
# JWT ATM
security.jwt.secret=${ATM_JWT_SECRET}
security.jwt.issuer=bff-atm
security.jwt.expiration-minutes=30

# Credenciales ATM
security.auth.username=${ATM_AUTH_USERNAME}
security.auth.password=${ATM_AUTH_PASSWORD}
# HTTPS
server.ssl.enabled=true
server.ssl.key-store=${SSL_KEYSTORE_PATH}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz-local