spring.application.name=bff-atm

server.port=8083

# API interna Banco XYZ
core.api.base-url=${CORE_API_BASE_URL:http://localhost:8080}

# Observabilidad
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
# OAuth2 Resource Server
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH_ISSUER_URI:http://localhost:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH_JWK_SET_URI:http://localhost:9000/oauth2/jwks}
# HTTPS
server.ssl.enabled=${SSL_ENABLED:true}
server.ssl.key-store=${SSL_KEYSTORE_PATH:}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz-local
# Resilience4j - Core API
spring.cloud.circuitbreaker.resilience4j.disable-time-limiter=true

resilience4j.circuitbreaker.instances.coreApi.register-health-indicator=true
resilience4j.circuitbreaker.instances.coreApi.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.coreApi.sliding-window-size=3
resilience4j.circuitbreaker.instances.coreApi.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.coreApi.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.coreApi.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.coreApi.permitted-number-of-calls-in-half-open-state=1
resilience4j.circuitbreaker.instances.coreApi.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.coreApi.ignore-exceptions=com.bancoxyz.bff.atm.exception.AtmRecursoNoEncontradoException,com.bancoxyz.bff.atm.exception.AtmSaldoInsuficienteException
